### ISSUE TITLE
Sync byte (55) repeated

### ISSUE THREAD

**Issue by obermann** [gmenounos/kw1281test#93]
KwpCommon.cs does not catch repeated sync byte 0x55. My cluster always repeat sync byte and a pair of key bytes if it receives response a bit later than ideal timing, and almost always does it even with ideal timing. On the second try it seems happy every time. I made a dirty, but 100% effective hack (since AFAIK KWP1281 block length would never be 0x55):
KW1281Dialog.cs
```
public Block ReceiveBlock()
...
var blockLength = ReadAndAckByteFirst();
...
        private byte ReadAndAckByte()
        {
            var b = KwpCommon.ReadByte();
            Thread.Sleep(TimeInterval.R6);
            var complement = (byte)~b;
            KwpCommon.WriteByte(complement);
            return b;
        }
        
        private byte ReadAndAckByteFirst(int count = 0)
        {
            if (count > 5)
            {
                throw new InvalidOperationException(
                    $"Cannot sync with {count} repeated attempts.");
            }
            var b = KwpCommon.ReadByte();
            if (b == 0x55)
            {
                var keywordLsb = KwpCommon.ReadByte();
                var keywordMsb = KwpCommon.ReadByte();
                BusyWait.Reset();
                var complement = (byte)~keywordMsb;
                BusyWait.Delay(25);
                KwpCommon.WriteByte(complement);
                Log.WriteLine($"Warning. Sync repeated.");
                return ReadAndAckByteFirst(count);
            }
            else
            {
                Thread.Sleep(TimeInterval.R6);
                var complement = (byte)~b;
                KwpCommon.WriteByte(complement);
                return b;
            }
        }
```
There should be a more elegant solution.

**Comment by gmenounos** [comment]
Thanks, I'll take a look at implementing this.

**Comment by gmenounos** [comment]
Sorry I haven't gotten to this yet. In the meantime, if you have a chance, please give the [latest release](https://github.com/gmenounos/kw1281test/releases/tag/v0.99.3-beta) a try as I fixed a bug that was causing out-of-spec wakeup timing.

**Comment by gmenounos** [comment]
Can you see if the [latest release](https://github.com/gmenounos/kw1281test/releases/tag/v0.99.5-beta) fixes your issue?

**Comment by Chris633000** [comment]
Hi, I still get an 
"Unexpected sync byte: Expected $55, Actual $F6"
using the latest [v0.99.5-beta]
Any Idea?

**Comment by Chris633000** [comment]
did work now...

**Comment by gmenounos** [comment]
@Chris633000 Usually when you get a response like "Unexpected sync byte: Expected $55, Actual $F6", it's because you've chose the wrong baud rate for the controller you're talking to. Most controllers operate at 10400 or 9600 baud.

**Comment by obermann** [comment]
You asked about v0.99.3-beta - answer is no, the changes did not help.
I see KW1281Dialog.cs is now patched with my hack and it works as expected.
Recently I had to hack the CCM to let people get out when a car was locked (disable "SAFELOCK" feature).
The problem showed up again just after sync, with first bytes being repeated by CCM.
There were no possible hacks left.
Then I tried a new notebook (x10 faster) and everything worked without a glitch.
I thought to myself - my old netbook (1 core 2 threads 32bit Atom CPU) is unique test for kw1281test and realtime .NET capability in general. Here are my findings:

- I used "Serial Port Monitor" (Electronic Team, Inc) and its timestamps show no delays. So, I lost confidence in software serial communication sniffers in general.
- I played with .NET Garbage Collection without any effects whatsoever. But one may learn the theory that GC indeed can ruin any realtime app and kw1281test may benefit from the strategic repeat of simple GC.Collect() (and less simple SustainedLowLatency).
- **The original problem (apparent delays in realtime serial communication at the start) on old netbook with Windows 7 is always present if .NET self-contained runtime assemblies are trimmed (.NET version 8 and 10).** The problem is extremely rare when kw1281test started with installed .NET Core or .NET Framework or Mono on Windows or Linux. Equivalent solution is to use `<TrimMode>copyused</TrimMode>` in cproj.
- It is hard to compile kw1281test for 32bit Linux.

I have no idea why trimming ruins realtime, never debugged IL code before, so I stopped here. If publishing untrimmed kw1281test feels as too big a distro, the problem and its solutions needs to be mentioned in documentation, because getting fast multicore machine to run command line 3 seconds app is counterintuitive.

**Comment by obermann** [comment]
Nowadays - yea. But I'm happy to say that your program definitely works on any pentium from the last millenium. If it would commit to more common standard, e.g. nestandard 2.0, there would be less big words like requirements or support.
True, I didn't test it with Windows 10 on my netbook and there is very slight chance that trimming on later Windows have different effect. Nevertheless, since writing realtime app for .NET is a challenge to the universe a thing with trimming and GC.Collect() are interesting.
